@host = http://localhost:8000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjdhZTVkYjUyZDcyYTE5MTQ5ZmMzN2IiLCJpYXQiOjE2MDE4ODk3NzAsImV4cCI6MTYwMTk1NDU3MH0.EYo2WaVDnVWfjsQrk2OmPYJhy_cWLYkaBY9wXWDQzDc

### get me 
GET {{host}}/user/me
Authorization: {{token}}

### register
POST {{host}}/user/register
Content-Type: application/json

{
    "name": "kiuj",
    "email" : "mhn@nnnn.com",
    "password" : "aA1!aaaa"
}

### login
POST {{host}}/user/login
Content-Type: application/json

{
    "email" : "mhn@nnnn.com",
    "password" : "aA1!aaaa"
}

### logout
Post {{host}}/user/logout
Content-Type: application/json
Authorization: {{token}}